flags:
  app.test.fdroid:
    carryforward: false

  app.test.googleplay:
    carryforward: false

  app.androidTest.fdroid:
    carryforward: false

  app.androidTest.googleplay:
    carryforward: false
