flags:
  test.fdroid:
    carryforward: false

  test.googleplay:
    carryforward: false

  androidTest.fdroid:
    carryforward: false

  androidTest.googleplay:
    carryforward: false

  permissions.androidTest.fdroid:
    carryforward: false

  permissions.androidTest.googleplay:
    carryforward: false
