name: codecov - test & androidTest
on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  coverage-fdroid:
    if: "!contains(github.event.head_commit.message, 'skip codecov fdroid')"

    name: coverage-fdroid
    runs-on: macos-latest
    timeout-minutes: 80

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: google-services.json
        env:
          GOOGLE_PLAY_JSON_DEVELOPMENT: ${{ secrets.GOOGLE_PLAY_JSON_DEVELOPMENT }}
        run: echo "${GOOGLE_PLAY_JSON_DEVELOPMENT}" | base64 -d > app/google-services.json

      - name: app
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 25
          target: default
          profile: Galaxy Nexus
          script: |
            adb logcat -c
            adb logcat > logcat.txt &
            ./gradlew -PgitHubAction :app:testFdroidDebugCombinedCoverage --stacktrace

      - name: artifact logcat
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: codecov-fdroid-logcat
          path: logcat.txt

      - name: artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: codecov-fdroid
          path: |
            **/build/reports/*
            **/build/outputs/*/connected/*

      - name: show .gradle size
        run: |
          set -x
          du -h -d 1 ~/.gradle

      - name: publish
        run: |
          set -x
          find . -name "*.exec"; find . -name "*.ec"; find app/build/reports/ -name "*.xml"
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f app/build/reports/FdroidDebug.xml -F app.froid

  coverage-googleplay:
    if: "!contains(github.event.head_commit.message, 'skip codecov googleplay')"

    name: coverage-googleplay
    runs-on: macos-latest
    timeout-minutes: 80

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: google-services.json
        env:
          GOOGLE_PLAY_JSON_DEVELOPMENT: ${{ secrets.GOOGLE_PLAY_JSON_DEVELOPMENT }}
        run: echo "${GOOGLE_PLAY_JSON_DEVELOPMENT}" | base64 -d > app/google-services.json

      - name: app
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 25
          target: default
          profile: Galaxy Nexus
          script: |
            adb logcat -c
            adb logcat > logcat.txt &
            ./gradlew -PgitHubAction :app:testGoogleplayDebugCombinedCoverage --stacktrace

      - name: artifact logcat
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: codecov-googleplay-logcat
          path: logcat.txt

      - name: artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: codecov-googleplay
          path: |
            **/build/reports/*
            **/build/outputs/*/connected/*

      - name: show .gradle size
        run: |
          set -x
          du -h -d 1 ~/.gradle

      - name: publish
        run: |
          set -x
          find . -name "*.exec"; find . -name "*.ec"; find app/build/reports/ -name "*.xml"
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f app/build/reports/GoogleplayDebug.xml -F app.googleplay
