name: composite-workflow

on:
  push:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: example
        uses: ./.github/actions/composite
